/**
 * @file main.c
 * @brief ESP32 HVCC Audio Integration
 * 
 * This application integrates Pure Data patches compiled with HVCC (Heavy Compiler)
 * to run on ESP32 hardware with I2S audio output.
 * 
 * Architecture:
 * - Pure Data patch (main.pd) -> HVCC compiler -> C code (output/c/)
 * - Heavy context processes audio in floating point
 * - Audio buffer converts float to int16 for I2S DAC output
 * - Runs at 48kHz stereo by default
 */

#include <stdio.h>
#include <stdbool.h>
#include <math.h>
#include <string.h>
#include "sdkconfig.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "driver/i2s_std.h"
#include "driver/gpio.h"
#include "esp_adc/adc_oneshot.h"
#include "cJSON.h"

// Heavy (HVCC) generated Pure Data patch interface
#include "output/c/Heavy_heavy.h"
#include "output/c/HvHeavy.h"

// Generated controls code (ADC, buttons, etc.)
#include "controls_generated.h"

// OLED Display
#include "oled_display.h"

// MIDI Handler
#include "midi_handler.h"

// ============================================================================
// CONFIGURATION
// ============================================================================

static const char *TAG = "HVCC";

// Audio Configuration
#define AUDIO_SAMPLE_RATE       48000   // Hz
#define AUDIO_BLOCK_SIZE        256     // samples (must be multiple of 8 for HVCC)
#define AUDIO_BIT_DEPTH         16      // bits

// I2S Pin Configuration (adjust for your hardware)
#define I2S_PIN_WORD_SELECT     GPIO_NUM_26  // LRCK/WS
#define I2S_PIN_BIT_CLOCK       GPIO_NUM_27  // BCLK
#define I2S_PIN_DATA_OUT        GPIO_NUM_25  // DOUT to DAC

// DMA Configuration
#define I2S_DMA_DESC_COUNT      4       // number of DMA descriptors
#define I2S_DMA_FRAME_COUNT     256     // samples per descriptor

// Control Configuration
// NOTE: Control pins and receivers are now configured via board_config.json
// and generated by generate_controls.py -> controls_generated.h/c

// ============================================================================
// AUDIO SUBSYSTEM
// ============================================================================

/**
 * @brief Audio system context
 * 
 * Encapsulates all state needed for audio processing pipeline
 */
typedef struct {
    i2s_chan_handle_t i2s_tx_channel;
    HeavyContextInterface *heavy_context;
    int num_output_channels;
    float *float_buffer;
    int16_t *output_buffer;
} audio_system_t;

static audio_system_t audio_sys = {0};

/**
 * @brief Initialize I2S hardware for audio output
 * 
 * Configures ESP32 I2S peripheral in master mode for stereo audio transmission
 * 
 * @return true on success, false on failure
 */
static bool audio_init_i2s(void) {
    ESP_LOGI(TAG, "Initializing I2S: %d Hz, %d-bit, stereo", 
             AUDIO_SAMPLE_RATE, AUDIO_BIT_DEPTH);
    
    // Configure I2S channel
    i2s_chan_config_t chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);
    chan_cfg.dma_desc_num = I2S_DMA_DESC_COUNT;
    chan_cfg.dma_frame_num = I2S_DMA_FRAME_COUNT;
    
    esp_err_t ret = i2s_new_channel(&chan_cfg, &audio_sys.i2s_tx_channel, NULL);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Failed to create I2S channel: %s", esp_err_to_name(ret));
        return false;
    }

    // Configure I2S standard mode (Philips I2S format)
    i2s_std_config_t std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(AUDIO_SAMPLE_RATE),
        .slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(
            I2S_DATA_BIT_WIDTH_16BIT, 
            I2S_SLOT_MODE_STEREO
        ),
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED,
            .bclk = I2S_PIN_BIT_CLOCK,
            .ws   = I2S_PIN_WORD_SELECT,
            .dout = I2S_PIN_DATA_OUT,
            .din  = I2S_GPIO_UNUSED,
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };
    std_cfg.slot_cfg.slot_mask = I2S_STD_SLOT_BOTH;
    
    ret = i2s_channel_init_std_mode(audio_sys.i2s_tx_channel, &std_cfg);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Failed to initialize I2S standard mode: %s", esp_err_to_name(ret));
        return false;
    }

    ret = i2s_channel_enable(audio_sys.i2s_tx_channel);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Failed to enable I2S channel: %s", esp_err_to_name(ret));
        return false;
    }

    ESP_LOGI(TAG, "I2S initialized successfully");
    return true;
}

/**
 * @brief Initialize Heavy (HVCC) audio processing context
 * 
 * Creates the Pure Data patch runtime and allocates audio buffers
 * 
 * @return true on success, false on failure
 */
static bool audio_init_heavy(void) {
    ESP_LOGI(TAG, "Initializing Heavy context...");
    
    // Create Heavy context with our sample rate
    audio_sys.heavy_context = hv_heavy_new((double)AUDIO_SAMPLE_RATE);
    if (!audio_sys.heavy_context) {
        ESP_LOGE(TAG, "Failed to create Heavy context");
        return false;
    }
    
    // Query output channel configuration
    audio_sys.num_output_channels = hv_getNumOutputChannels(audio_sys.heavy_context);
    if (audio_sys.num_output_channels <= 0) {
        ESP_LOGW(TAG, "Patch declares no output channels, defaulting to mono");
        audio_sys.num_output_channels = 1;
    }
    
    // Allocate audio processing buffers
    size_t float_buffer_size = AUDIO_BLOCK_SIZE * audio_sys.num_output_channels;
    audio_sys.float_buffer = (float *)malloc(float_buffer_size * sizeof(float));
    
    size_t output_buffer_size = AUDIO_BLOCK_SIZE * 2;  // stereo
    audio_sys.output_buffer = (int16_t *)malloc(output_buffer_size * sizeof(int16_t));
    
    if (!audio_sys.float_buffer || !audio_sys.output_buffer) {
        ESP_LOGE(TAG, "Failed to allocate audio buffers");
        return false;
    }
    
    ESP_LOGI(TAG, "Heavy context ready: %d channels, %d samples/block", 
             audio_sys.num_output_channels, AUDIO_BLOCK_SIZE);
    return true;
}

/**
 * @brief Initialize ADC for control inputs
 * 
 * Delegates to generated controls code (controls_init_adc)
 * which reads configuration from board_config.json
 * 
 * @return true on success, false on failure
 */
static bool audio_init_adc(void) {
    ESP_LOGI(TAG, "Initializing controls from board_config.json");
    return controls_init_adc(audio_sys.heavy_context);
}

/**
 * @brief Clip audio sample to prevent distortion
 * 
 * @param sample Input sample value
 * @return Clipped sample in range [-1.0, 1.0]
 */
static inline float audio_clip_sample(float sample) {
    if (sample > 1.0f) return 1.0f;
    if (sample < -1.0f) return -1.0f;
    return sample;
}

/**
 * @brief Convert float audio to int16 and interleave stereo
 * 
 * Takes planar float audio from Heavy and converts to interleaved
 * int16 stereo format required by I2S DAC
 * 
 * @param float_in Input float buffer (planar)
 * @param int16_out Output int16 buffer (interleaved stereo)
 * @param num_frames Number of audio frames to convert
 */
static void audio_convert_to_i2s_format(const float *float_in, int16_t *int16_out, 
                                         int num_frames) {
    for (int i = 0; i < num_frames; i++) {
        // Get left channel
        float left = audio_clip_sample(float_in[i]);
        
        // Get right channel (duplicate left if mono)
        float right = (audio_sys.num_output_channels >= 2) 
                      ? audio_clip_sample(float_in[i + num_frames])
                      : left;
        
        // Convert to int16 and interleave: [L, R, L, R, ...]
        int16_out[2 * i]     = (int16_t)(left * 32767.0f);
        int16_out[2 * i + 1] = (int16_t)(right * 32767.0f);
    }
}

/**
 * @brief Control input processing task
 * 
 * Delegates to generated controls code (controls_task)
 * which handles all ADC polling and Pure Data receiver messaging
 */
static void control_task(void *arg) {
    controls_task(arg);
}

// OLED configuration loaded from JSON
static oled_config_t oled_config = {0};
static hv_uint32_t oled_table_hashes[OLED_MAX_DISPLAYS] = {0};

// MIDI configuration loaded from JSON
static midi_config_t midi_config = {0};

/**
 * @brief Load MIDI configuration from embedded board_config.json
 */
static bool load_midi_config(void) {
    extern const char board_config_json_start[];
    cJSON *root = cJSON_Parse(board_config_json_start);
    if (!root) {
        ESP_LOGE(TAG, "Failed to parse board_config for MIDI");
        return false;
    }

    cJSON *midi = cJSON_GetObjectItem(root, "midi");
    if (!midi) {
        ESP_LOGI(TAG, "No MIDI configuration found in board_config");
        cJSON_Delete(root);
        return false;
    }

    // Parse transport type
    cJSON *transport = cJSON_GetObjectItem(midi, "transport");
    if (transport && cJSON_IsString(transport)) {
        const char *transport_str = transport->valuestring;
        if (strcmp(transport_str, "uart") == 0) {
            midi_config.transport = MIDI_TRANSPORT_UART;
        } else if (strcmp(transport_str, "usb") == 0) {
            midi_config.transport = MIDI_TRANSPORT_USB;
        } else {
            midi_config.transport = MIDI_TRANSPORT_NONE;
        }
    }

    // Parse UART pins
    cJSON *uart_tx = cJSON_GetObjectItem(midi, "uart_tx_pin");
    cJSON *uart_rx = cJSON_GetObjectItem(midi, "uart_rx_pin");
    if (uart_tx && cJSON_IsNumber(uart_tx)) {
        midi_config.uart_tx_pin = uart_tx->valueint;
    }
    if (uart_rx && cJSON_IsNumber(uart_rx)) {
        midi_config.uart_rx_pin = uart_rx->valueint;
    }

    // Parse enable flags
    cJSON *enable_input = cJSON_GetObjectItem(midi, "enable_input");
    cJSON *enable_output = cJSON_GetObjectItem(midi, "enable_output");
    midi_config.enable_input = (enable_input && cJSON_IsBool(enable_input)) ? cJSON_IsTrue(enable_input) : false;
    midi_config.enable_output = (enable_output && cJSON_IsBool(enable_output)) ? cJSON_IsTrue(enable_output) : false;

    cJSON_Delete(root);

    ESP_LOGI(TAG, "MIDI config loaded: transport=%d, TX=%d, RX=%d, in=%d, out=%d",
             midi_config.transport, midi_config.uart_tx_pin, midi_config.uart_rx_pin,
             midi_config.enable_input, midi_config.enable_output);
    return true;
}

/**
 * @brief Load OLED configuration from embedded board_config.json
 */
extern const char board_config_json_start[];
extern const char board_config_json_end[];

static bool load_oled_config(void) {
    const char *json_str = board_config_json_start;
    size_t json_len = strlen(json_str);
    
    ESP_LOGI(TAG, "Loading OLED config from JSON (%u bytes)...", json_len);
    
    cJSON *root = cJSON_ParseWithLength(json_str, json_len);
    if (!root) {
        ESP_LOGE(TAG, "Failed to parse board_config.json");
        return false;
    }
    
    cJSON *oled = cJSON_GetObjectItem(root, "oled");
    if (!oled) {
        ESP_LOGW(TAG, "No 'oled' section in config - using defaults");
        cJSON_Delete(root);
        return false;
    }
    
    // Parse SPI pins
    cJSON *spi = cJSON_GetObjectItem(oled, "spi");
    if (spi) {
        oled_config.mosi_pin = cJSON_GetObjectItem(spi, "mosi")->valueint;
        oled_config.clk_pin = cJSON_GetObjectItem(spi, "clk")->valueint;
        oled_config.dc_pin = cJSON_GetObjectItem(spi, "dc")->valueint;
        oled_config.rst_pin = cJSON_GetObjectItem(spi, "rst")->valueint;
    } else {
        ESP_LOGE(TAG, "Missing 'spi' section in OLED config");
        cJSON_Delete(root);
        return false;
    }
    
    // Parse displays
    cJSON *displays = cJSON_GetObjectItem(oled, "displays");
    if (!displays || !cJSON_IsArray(displays)) {
        ESP_LOGE(TAG, "Missing or invalid 'displays' array");
        cJSON_Delete(root);
        return false;
    }
    
    int num_displays = cJSON_GetArraySize(displays);
    if (num_displays > OLED_MAX_DISPLAYS) {
        num_displays = OLED_MAX_DISPLAYS;
    }
    oled_config.num_displays = num_displays;
    
    for (int i = 0; i < num_displays; i++) {
        cJSON *disp = cJSON_GetArrayItem(displays, i);
        oled_display_config_t *disp_cfg = &oled_config.displays[i];
        
        disp_cfg->id = cJSON_GetObjectItem(disp, "id")->valueint;
        disp_cfg->cs_pin = cJSON_GetObjectItem(disp, "cs_pin")->valueint;
        
        // Parse value_min and value_max for scaling (optional, defaults to 0 and 1)
        cJSON *value_min_item = cJSON_GetObjectItem(disp, "value_min");
        cJSON *value_max_item = cJSON_GetObjectItem(disp, "value_max");
        disp_cfg->value_min = (value_min_item) ? (float)value_min_item->valuedouble : 0.0f;
        disp_cfg->value_max = (value_max_item) ? (float)value_max_item->valuedouble : 1.0f;
        
        cJSON *table_name = cJSON_GetObjectItem(disp, "table_name");
        if (table_name && cJSON_IsString(table_name) && table_name->valuestring) {
            strncpy(disp_cfg->table_name, table_name->valuestring, sizeof(disp_cfg->table_name) - 1);
            disp_cfg->table_name[sizeof(disp_cfg->table_name) - 1] = '\0';
            
            // Pre-compute hash for this table
            if (disp_cfg->table_name[0] != '\0') {
                oled_table_hashes[i] = hv_stringToHash(disp_cfg->table_name);
                ESP_LOGI(TAG, "Display %d: table '%s' hash = 0x%08lx", 
                         i, disp_cfg->table_name, oled_table_hashes[i]);
            }
        } else {
            disp_cfg->table_name[0] = '\0';
        }
    }
    
    cJSON_Delete(root);
    
    ESP_LOGI(TAG, "OLED config loaded: %d display(s)", oled_config.num_displays);
    return true;
}

/**
 * @brief Heavy send hook - handles outgoing messages from Pure Data
 * 
 * Called when messages are sent to [s receiver] objects in the patch.
 * Routes MIDI output messages and can handle custom receivers.
 */
static void heavy_send_hook(HeavyContextInterface *context, const char *receiverName, 
                           uint32_t receiverHash, const HvMessage *m) {
    // Handle MIDI output messages
    if (midi_is_ready()) {
        midi_handle_heavy_send(receiverHash, m);
    }
    
    // Add custom receiver handling here if needed
    // For example:
    // if (receiverHash == HV_HASH_MYRECEIVER) {
    //     float value = hv_msg_getFloat(m, 0);
    //     // Do something with value
    // }
}

/**
 * @brief OLED display update task
 * 
 * Periodically updates both OLED displays with Hello World and random info
 */
static void oled_task(void *arg) {
    ESP_LOGI(TAG, "OLED task started - updating %d displays every 1 second", oled_config.num_displays);
    
    while (true) {
        // Update each display
        for (uint8_t i = 0; i < oled_config.num_displays; i++) {
            const oled_display_config_t *disp = &oled_config.displays[i];
            
            // If this display has a table assigned, read it
            if (disp->table_name[0] != '\0' && oled_table_hashes[i] != 0) {
                float *table_buf = hv_table_getBuffer(audio_sys.heavy_context, oled_table_hashes[i]);
                hv_uint32_t table_len = hv_table_getLength(audio_sys.heavy_context, oled_table_hashes[i]);
                if (table_buf && table_len > 0) {
                    oled_set_table_data(table_buf, table_len);
                }
            }
            
            oled_update_display(i);
        }
        
        vTaskDelay(pdMS_TO_TICKS(1000));  // Update every 1 second
    }
}

/**
 * @brief Main audio processing and output loop
 * 
 * Continuously processes audio through Heavy context and outputs to I2S.
 * This function never returns.
 */
static void audio_processing_loop(void) {
    ESP_LOGI(TAG, "Starting audio processing loop");
    
    size_t bytes_to_write = AUDIO_BLOCK_SIZE * 2 * sizeof(int16_t);  // stereo
    size_t bytes_written;
    
    while (true) {
        // Process MIDI input/output
        if (midi_is_ready()) {
            midi_process();
        }
        
        // Process audio block through Heavy (Pure Data) patch
        int frames_processed = hv_processInline(
            audio_sys.heavy_context,
            NULL,                       // no input
            audio_sys.float_buffer,     // output buffer
            AUDIO_BLOCK_SIZE            // frames to process
        );
        
        if (frames_processed <= 0) {
            // No audio generated, yield to other tasks
            vTaskDelay(pdMS_TO_TICKS(1));
            continue;
        }

        // Compute audio levels for display 1
        float sum_l = 0.0f;
        float sum_r = 0.0f;
        float peak = 0.0f;
        for (int i = 0; i < frames_processed; i++) {
            float left = audio_clip_sample(audio_sys.float_buffer[i]);
            float right = (audio_sys.num_output_channels >= 2)
                          ? audio_clip_sample(audio_sys.float_buffer[i + frames_processed])
                          : left;
            sum_l += left * left;
            sum_r += right * right;

            float abs_l = fabsf(left);
            float abs_r = fabsf(right);
            if (abs_l > peak) peak = abs_l;
            if (abs_r > peak) peak = abs_r;
        }
        float rms_l = sqrtf(sum_l / (float)frames_processed);
        float rms_r = sqrtf(sum_r / (float)frames_processed);
        oled_set_audio_levels(rms_l, rms_r, peak);
        
        // Convert float to int16 and interleave for I2S
        audio_convert_to_i2s_format(
            audio_sys.float_buffer,
            audio_sys.output_buffer,
            frames_processed
        );
        
        // Write to I2S DAC
        esp_err_t ret = i2s_channel_write(
            audio_sys.i2s_tx_channel,
            audio_sys.output_buffer,
            bytes_to_write,
            &bytes_written,
            portMAX_DELAY
        );
        
        if (ret != ESP_OK || bytes_written != bytes_to_write) {
            ESP_LOGW(TAG, "I2S write incomplete: %d bytes of %d", 
                     bytes_written, bytes_to_write);
            vTaskDelay(pdMS_TO_TICKS(1));
        }
    }
}

// ============================================================================
// MAIN APPLICATION
// ============================================================================

/**
 * @brief Application entry point
 * 
 * Initializes audio subsystem and starts processing loop
 */
void app_main(void) {
    ESP_LOGI(TAG, "========================================");
    ESP_LOGI(TAG, "ESP32 HVCC Audio Application Starting");
    ESP_LOGI(TAG, "========================================");
    
    // Initialize I2S hardware
    if (!audio_init_i2s()) {
        ESP_LOGE(TAG, "I2S initialization failed - halting");
        return;
    }
    
    // Initialize Heavy (Pure Data) audio engine
    if (!audio_init_heavy()) {
        ESP_LOGE(TAG, "Heavy initialization failed - halting");
        return;
    }
    
    // Initialize ADC and button controls
    bool adc_ok = audio_init_adc();
    bool btn_ok = controls_init_buttons();

    if (!adc_ok) {
        ESP_LOGW(TAG, "ADC initialization failed - knob controls may not work");
    }
    if (!btn_ok) {
        ESP_LOGW(TAG, "Button initialization failed - button controls may not work");
    }

    if (adc_ok || btn_ok) {
        // Start control input task with Heavy context
        xTaskCreate(control_task, "controls", 2048, audio_sys.heavy_context, 5, NULL);
    } else {
        ESP_LOGW(TAG, "No controls initialized - skipping controls task");
    }
    
    // Load OLED configuration and initialize display
    if (load_oled_config() && oled_init(&oled_config)) {
        ESP_LOGI(TAG, "OLED display initialized - starting update task");
        xTaskCreate(oled_task, "oled_display", 4096, NULL, 3, NULL);
    } else {
        ESP_LOGW(TAG, "OLED initialization failed - display will not be available");
    }

    // Load MIDI configuration and initialize
    if (load_midi_config() && midi_init(&midi_config, audio_sys.heavy_context)) {
        ESP_LOGI(TAG, "MIDI initialized successfully");
        // Set send hook to handle MIDI output from Pure Data
        hv_setSendHook(audio_sys.heavy_context, heavy_send_hook);
    } else {
        ESP_LOGI(TAG, "MIDI not configured or initialization failed");
    }
    
    ESP_LOGI(TAG, "All systems ready - starting audio output");
    ESP_LOGI(TAG, "========================================");
    
    // Run audio loop (never returns)
    audio_processing_loop();
}
